name: felxisip

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-noble

    steps:
    - uses: actions/checkout@v4
    - name: Build the flexisip Docker image
      run: docker build . --file Dockerfile_flexisip_install --tag my-image-name:$(date +%s)
